version: '3'
services:
  frontend_futzo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: futzo-front
    ports:
      - '${FRONT_PORT:-3000}:3000'
      - '24678:24678'
    volumes:
      - '.:/var/www/html'
    networks:
      - sls-api_futzo_network
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_URL_BACKEND=http://futzo-api.test
      - NUXT_PUBLIC_BACKEND_PREFIX=api/v1
      - FACEBOOK_APP_ID=624608699554291
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend_futzo.rule=Host(`frontend.futzo.test`)"
      - "traefik.http.routers.frontend_futzo.service=frontend_futzo"
      - "traefik.http.services.frontend_futzo.loadbalancer.server.port=3000"

networks:
  sls-api_futzo_network:
    external: true