<script setup lang="ts">
  import { fetchTickets } from '~/http/api/support'
  import type { Tickets } from '~/models/Support'
  const { user } = storeToRefs(useAuthStore())
  const tickets = ref<Tickets>({} as Tickets)
  watch(
    () => user.value,
    async (newUser) => {
      if (newUser?.opened_tickets_count && newUser?.opened_tickets_count > 0) {
        tickets.value = await fetchTickets()
      }
    },
    { immediate: true }
  )
</script>

<template>
  <v-card v-for="ticket in tickets.data" :key="ticket.id" class="mb-4">
    <v-card-item>
      <v-card-title
        ><div class="d-flex">
          Ticket #{{ ticket.id.substring(1, 8) }} <v-spacer />
          <span class="text-info text-caption">{{ ticket.subject }}</span>
        </div>
      </v-card-title>
      <v-card-subtitle> Creado {{ ticket.created_at }} </v-card-subtitle>
      <div class="py-4 d-flex align-center">
        <Icon :name="`mdi-${ticket.contact_method === 'email' ? 'email-outline' : 'phone-outline'}`" size="20"></Icon>
        <p class="text-body-1 mx-2">{{ ticket.contact_value }}</p>
        <span class="mx-2">|</span>
        <Icon name="mdi-message-outline" size="20" class="mx-2"></Icon>
        <p class="text-body-1 mx-2">{{ ticket.messages_count }}</p>
      </div>
    </v-card-item>
    <v-card-text>
      <v-timeline side="end">
        <v-timeline-item
          v-for="message in ticket.public_messages"
          :key="message.id"
          :dot-color="message.author_type === 'user' ? 'primary' : 'grey-lighten-1'"
          :icon="`mdi-${message.author_type === 'user' ? 'account' : 'robot'}`"
          size="small"
        >
          <v-card variant="outlined" class="futzo-rounded">
            <v-card-title :class="`text-${message.author_type === 'user' ? 'primary' : 'green-lighten-1'}`">
              <div class="d-flex justify-space-between">
                <p class="text-body-1">{{ message.author_type === 'user' ? 'Tu' : 'Futzo' }}</p>
                <div class="d-flex align-center justify-content-center text-secondary">
                  <Icon name="mdi-clock-outline" size="16" />
                  <p class="text-caption ml-2">
                    {{ message.created_at }}
                  </p>
                </div>
              </div>
            </v-card-title>
            <v-card-text>
              {{ message.body }}
            </v-card-text>
          </v-card>
        </v-timeline-item>
      </v-timeline>
      <div class="d-flex align-center my-2">
        <span class="pulse pulsate-fwd bg-green-lighten-2 mx-2"></span>
        <span>Esperando respuesta del equipo de soporte</span>
      </div>
    </v-card-text>
    <v-card-actions>
      <div class="d-flex flex-column w-100">
        <v-textarea variant="outlined" class="my-4"> </v-textarea>
        <PrimaryBtn
          block
          text="Enviar mensaje"
          icon="mdi-send"
          iconPosition="right"
          :disabled="ticket.status === 'open'"
        />
      </div>
    </v-card-actions>
  </v-card>
</template>

<style scoped>
  .pulse {
    width: 10px;
    height: 10px;
    border-radius: 50%;
  }
  .pulsate-fwd {
    -webkit-animation: pulsate-fwd 0.5s ease-in-out infinite both;
    animation: pulsate-fwd 0.5s ease-in-out infinite both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2026-1-26 1:5:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation pulsate-fwd
   * ----------------------------------------
   */
  @-webkit-keyframes pulsate-fwd {
    0% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
    50% {
      -webkit-transform: scale(1.1);
      transform: scale(1.1);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
  @keyframes pulsate-fwd {
    0% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
    50% {
      -webkit-transform: scale(1.1);
      transform: scale(1.1);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
</style>
